# Generated by Django 4.1.1 on 2022-09-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nme', models.CharField(max_length=25)),
                ('phone', models.IntegerField(max_length=10)),
                ('college', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=30)),
                ('no', models.IntegerField(max_length=10)),
                ('oid', models.CharField(max_length=100)),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
