# Generated by Django 4.1.1 on 2022-09-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
